In [4]:
import torch
torch.__version__

'2.2.0'

In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
matrix = torch.tensor([[7,8], [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[1, 2, 3],
 [3, 6, 9],
 [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [14]:
# create a random tensor
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.2228, 0.5951, 0.8504, 0.4656],
        [0.0724, 0.1018, 0.5989, 0.5537],
        [0.9926, 0.6990, 0.8652, 0.2096]])

In [15]:
random_tensor.dtype

torch.float32

In [16]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))

In [17]:
zeros = torch.zeros(size=(3,2))
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [19]:
ones = torch.ones(size=(3,2))
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [20]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
ten_zeros.device

device(type='cpu')

In [23]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [24]:
tensor *10

tensor([10, 20, 30])

In [25]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1,2,3])
t1 * t2

tensor([1, 4, 9])

In [28]:
(t1 @ t2).item()

14

In [29]:
torch.matmul(t1, t2)

tensor(14)

## Lab Exercise:

1. Illustrate the functions for Reshaping, viewing, stacking, squeezing and unsqueezing of tensors

In [38]:
a = torch.tensor([1,2,3,4,5,6,7,8,9])
print(a)
print(a.shape)
a = a.reshape([3,3])
print(a.shape)
print(a)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [44]:
b = torch.FloatTensor([10, 20, 30, 40, 50, 1, 2, 3, 4, 5])
print(b.view(5, 2))

tensor([[10., 20.],
        [30., 40.],
        [50.,  1.],
        [ 2.,  3.],
        [ 4.,  5.]])


In [45]:
x = torch.tensor([1.,3.,6.,10.]) 
y = torch.tensor([2.,7.,9.,13.])
t = torch.stack(tensors=(x,y))
t

tensor([[ 1.,  3.,  6., 10.],
        [ 2.,  7.,  9., 13.]])

In [47]:
input = torch.randn(3,1,2,1,4)
print(input)

output = torch.squeeze(input)
print('output:')
print(output)

tensor([[[[[-0.9065,  0.4270, -1.0608, -0.8369]],

          [[ 0.0568, -0.1589, -0.0296,  2.1912]]]],



        [[[[ 0.4380, -0.9097,  0.7353, -0.7700]],

          [[ 0.3918,  0.9068, -0.2501,  0.4130]]]],



        [[[[ 0.7608, -0.6542, -1.9473, -1.0219]],

          [[ 0.6869,  0.1994, -1.6300,  0.7268]]]]])
output:
tensor([[[-0.9065,  0.4270, -1.0608, -0.8369],
         [ 0.0568, -0.1589, -0.0296,  2.1912]],

        [[ 0.4380, -0.9097,  0.7353, -0.7700],
         [ 0.3918,  0.9068, -0.2501,  0.4130]],

        [[ 0.7608, -0.6542, -1.9473, -1.0219],
         [ 0.6869,  0.1994, -1.6300,  0.7268]]])


In [50]:
input = torch.arange(8, dtype=torch.float)
output = torch.unsqueeze(input, dim=1)
print(output)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])


2) Illustrate the use of torch.permute().

In [52]:
input_var = torch.randn(3, 5, 2)
print(input_var.size())
input_var = input_var.permute(2,0,1)
print(input_var.size())

torch.Size([3, 5, 2])
torch.Size([2, 3, 5])


In [56]:
# Perform a matrix multiplication

In [57]:
mat_1 = torch.tensor([[1, 2], 
                      [4, 3]]) 
  
mat_2 = torch.tensor([[2, 4, 1], 
                      [1, 3, 6]]) 
  
torch.mm(mat_1, mat_2, out=None) 

tensor([[ 4, 10, 13],
        [11, 25, 22]])

In [58]:
import numpy as np
def grad_sigmoid_manual(x):
    a = -x
    b = np.exp(a)
    c = 1+b
    s = 1.0/c
    
    dsdc = (-1.0 / (c**2))
    dsdb = dsdc * 1
    dsda = dsdb * np.exp(a)
    dsdx = dsda * (-1)
    return dsdx

def sigmoid(x):
    y = 1.0 / (1.0 + torch.exp(-x))
    return y

input_x = 2.0
x = torch.tensor(input_x).requires_grad_(True)
y = sigmoid(x)
y.backward()
print('autograd:', x.grad.item())
print('manual:', grad_sigmoid_manual(input_x))
    

autograd: 0.10499356687068939
manual: 0.1049935854035065


1. Draw Computation Graph and work out the gradient dz/da by following the path 
back from z to a and compare the result with the analytical gradient. 
x = 2*a + 3*b
y = 5*a*a + 3*b*b*b
z = 2*x + 3*y

In [59]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(2.0, requires_grad=True)

x = 2*a + 3*b
y = 5*a*a + 3*b*b*b
z = 2*x + 3*y

z.backward()
print(a.grad, b.grad)

def manual(x):
    x = 2*a + 3*b
    y = 5*a*a + 3*b*b*b

tensor(64.) tensor(114.)
